### ISSUE TITLE
Run DAQ.py on Raspberry Pi Startup

### ISSUE THREAD

**Issue by bellh14** [DallasFormulaRacing/LabJackCanBus#10]
The raspberry pi 4 is running a version of Debian Linux. Research how to run the python file on startup and come to the shop and implement it on the pi directly. 

This should be fairly easy and will be good exposure if you have never used Linux based operating systems before or the command line. 

Optionally add in a way to check if the program is running.  Could be save a file with the date and time of starting the program if the script starts successfully or an error message in the file if failed.

**Comment by Squidtoon99** [comment]
Code autostarts on boot through systemd
