### ISSUE TITLE
Migrate to Streams

### ISSUE THREAD

**Issue by Squidtoon99** [DallasFormulaRacing/LabJackCanBus#20]
LabJack Streams are much faster and more consistent than polling methods. This feature closely aligns with our requirements and will allow us to massively increase the rate of data ingestion while freeing up Rasberry PI processing for other features.

## Core Functionality
- [x] Basic Stream support
- [x] Error Handling(+retries)
- [x] Abstract Classes for modularity
- [ ] Upload to endpoint (wss/https)

## Sensors
- [x] Linpots
- [x] Accelerometers
- [ ] Gyro

## Enhancements
- [x] Python Logging #17 
- [x] Documentation
- [x] Clear Comments

**Comment by GHAFHA** [comment]
Nico will be contributing to this starting Monday, specifically he will be working on converting the accelerometer code over to i2c and enabling gyro
